### ISSUE TITLE
Performance PRs to be ported to the master

### ISSUE THREAD

**Issue by hassount** [OpenVisualCloud/SVT-AV1#1047]
@hguermaz
- [x] Spatial Domain Distortion @ only the last stage (PD2/MD_STAGE_3) (#1057)
- [x] Remove layer check(s) @ PD1 settings derivation (#1057)
- [x] Tx Size Search Depth_2 INTRA/INTER 8BIT/10BIT (#1060)
- [x] TXS/RDOQ for block_copy (#1060)
- [x] Rate Estimation Bug Fixes (#1060)
- [x] Improve Nx4 & 4xN INTER candidates injection, and 1/8 Pel ME MVs refinement (#1063)
- [x] Signal(s) clean-up. (#1080)
- [x] IFS at last MDS. (#1113)
- [x] QPS (#1117 )
- [x] plane-wise Altref,, tf ME swicth , packing. (#1120 )

@ttrigui 
- [x] 16bit-pipeline (#1138)

@phoenixworthVCD
- [x] sq weight (#1006 )
- [x] mds 3 (#1009 )
- [x] rdoq opt / quant fp enhancement (#1002 )
- [x] tx size code refactoring ... (#1010 )

@okhlif
- [x] ME Search_Area = f(temporal_distance, frame_rate), HME for 360p.(#1067)
- [x] SB128x128 for 360p. (#1110 )
- [x] Lambda for 10BIT. (#1119)
- [x] NIC Levels (enhancements and refactor) (#1069)
- [x] ME-based ref frames pruning. (#1070 )
- [x] HP/QP Switch. (#1070 )

@nadermahdi
- [x] Optimized Chroma Search. (#1071)
- [x] Skip Depth @ PD2. (#1111)
- [x] NSQ Opt @ Full & Sub Pel. (#1112)

@chkngit 
- [x] ME-based ref frames pruning. (#1040)
- [x] compound similar candidates (#1058)
- [x] intra similar candidates (#1058)
- [x] nsq weight (#1121)

@lijing0010 
- [x] 31B MRP (#1072)

@anaghdin 
- [x] alt-ref enhancement (#997 )
- [x] warped motion enhancement (#1015)
- [x] md rate estimation (#979 )
- [x] qps for incomplete GOP (#1033)

@OmranAbdelkafi 
- [x] structures cleanup (commit c80b6f0 from the cs2 branch) (#1140 )
- [x] cli enhancements (commit 77a40c9 from the cs2 branch) (#1141 )

**Comment by hguermaz** [comment]
- [HG] Tx Size Search Depth_2 INTRA/INTER 8BIT/10BIT.
- [HG] Spatial Domain Distortion @ only the last stage (PD2/MD_STAGE_3).
- [HG] Rate Estimation Bug Fixes.
- [HG] Improve Nx4 & 4xN INTER candidates injection, and 1/8 Pel ME MVs refinement.
- [HG] Remove useless NSQ signal(s): nsq_level, is_nsq_table_used. 

- [OK] ME Search_Area = f(temporal_distance, frame_rate), HME for 360p.
- [OK] SB128x128 for 360p.
- [OK] Lambda for 10BIT.
- [OK] NIC Levels (enhancements and refactor)
- [OK] SC Preset(s).
- [OK] Clean-up pic_obmc_mode derivation.

- [PW] NSC Preset(s).
- [PW] Remove useless MR_MODE checks.

- [NM] Optimized Chroma Search.
- [NM] ME-based ref frames pruning. 
- [NM] Link the 3 GM signals into 1: gm_level, compute_global_motion, global_mv_injection.

- [AN] MRP indices enhancements.
- [AN] Non-5L stability/fixes.
- [AN] QPS for incomplete GOP.

**Comment by hassount** [comment]
will open a new issue to track items for the next tag
