### ISSUE TITLE
Next round of PRs before 0.8.4

### ISSUE THREAD

**Issue by hassount** [OpenVisualCloud/SVT-AV1#1234]
@phoenixworthVCD
- [x] Update NSC Preset(s). (#1149)
- [x] Update SC Preset(s). (#1149)
- [x] SC HME Pruning. (#1149 )

@lijing0010 
- [ ] MRP indices enhancements.
- [ ] non-5L / LDP stability/fixes.

@fouedb 
- [ ]  0B Tuning

**Comment by 1480c1** [comment]
Maybe this should be moved to 0.8.5 or closed?
