### ISSUE TITLE
Add continuous integration

### ISSUE THREAD

**Issue by EwoutH** [OpenVisualCloud/SVT-AV1#4]
First of all, huge kudo's to Intel for developing this open source, and kudo's to the people who pushed it inside Intel. It really makes AV1 an amazing example of how symbiotic development is a viable business model.

Aside from that, it would be very nice to have a very solid CI/CD implementation. My current, primitive proposal is to use the following tools:

- [x] Integrate Jenkins server (@kylophone? see [this guide](https://resources.github.com/whitepapers/practical-guide-to-CI-with-Jenkins-and-GitHub/))
- Building & testing with Travis CI
   - [x] Linux (PR #16)
   - [x] macOS (PR #25)
- [x] Building, testing & delivering on Windows with AppVeyor (PR #14)
- [x] Building Linux packages with Snapcraft (PR submitted: #38)
- Coveralls for code coverage
   - [x] Implement coverage framework (PR #25)
   - [x] Add first tests (@andrey-norkin)
- [x] Bit-exact output agains master branch (PR #376)
- [x] Measure encoding quality, speed and efficiency with [AWCY](https://github.com/tdaede/awcy).

Any suggestions on how to improve the continuous integration, testing and delivery are welcome!

**Comment by kylophone** [comment]
Hi,

> First of all, huge kudo's to Intel for developing this open scource, and kudo's to the people who pushed it inside Intel. It really makes AV1 an amazing example of how symbiotic development is a viable business model.
> 
> Aside from that, it would be very nice to have a very solid CI/CD implementation. My current, primitive proposal is to use the following tools:
> 
> * Building & testing on Linux & macOS with Travis CI
> * Building, testing & delivering on Windows with AppVeyor
> * Coveralls for code coverage
> * Bit-exact decodability tested against both aomdec and dav1d.
> 
> Travis and AppVeyor could I implement on monday, and coveralls probably also. But please use this issue to discuss optimal implementations that cover an as large portion of the code base and usage scenario's as possible.

Yes, all of these things are needed. A Jenkins server already exists for CI, but needs to be integrated into this new repo. You'll notice the test coverage is non-existent right now, that will be changing soon. I like the idea of adding a Coveralls and AppVeyor build as well. I'll keep this issue open until all this stuff is integrated. Other suggestions are welcome, too.

Thanks,
Kyle

**Comment by kylophone** [comment]
> * [ ]  Building & testing on Linux & macOS with Travis CI
In addition to these two platforms, the hope is to add Windows to CI as well.

**Comment by EwoutH** [comment]
@kylophone PR #14 does that :).

Now working on Linux (Ubuntu 16.04), macOS will follow later.

**Comment by EwoutH** [comment]
@kylophone could you link the Jenkins server to GitHub? This guide should be useful: https://resources.github.com/whitepapers/practical-guide-to-CI-with-Jenkins-and-GitHub/

**Comment by kylophone** [comment]
> @kylophone could you link the Jenkins server to GitHub? This guide should be useful: https://resources.github.com/whitepapers/practical-guide-to-CI-with-Jenkins-and-GitHub/

Could, but I think Travis might be the better bet going forward (and should be an easy way to get MacOS and Windows CI builds.) For context, our Jenkins server was self-hosted on AWS. It would be nice to avoid the manual sysadmin tasks involved with self-hosting a set of CI servers for 3 platforms. Thanks for kicking this effort off!

**Comment by kylophone** [comment]
> @kylophone Thanks for merging #16! Because I used the word _resolves_ in that PR, it automatically closed this issue, Can you reopen it? 
 Reopened. That's kinda funny, thanks Github.

**Comment by EwoutH** [comment]
It would also be really useful to integrate [AWCY](https://github.com/tdaede/awcy) (Are We Compressed Yet?) to continuously measure encoding quality, speed and efficency. Not my area of expertise though.

**Comment by kylophone** [comment]
> It would also be really useful to integrate [AWCY](https://github.com/tdaede/awcy) (Are We Compressed Yet?) to continuously measure encoding quality, speed and efficency. Not my area of expertise though.

Yep, SVT-AV1 has already been integrated:
https://beta.arewecompressedyet.com/?job=feb4_compound_p5_2_c4%402019-02-04T13%3A37%3A48.807Z&job=svt-av1-1&job=master-336a7d6a4f0996a1b177592cd65e178bb6c0d99a

**Comment by EwoutH** [comment]
@kylophone Nice! I will look into if AWCY can be better integrated with GitHub somehow.

It looks like Coveralls isn't activated yet, when [enabled](https://github.com/marketplace/coveralls) on the GitHub Marketplace it can be [activated](https://coveralls.io/repos/new) (when logged in) on coveralls.io and should appear working [here](https://coveralls.io/github/OpenVisualCloud/SVT-AV1).

**Comment by EwoutH** [comment]
@kylophone @hassount Can Coveralls be enabled (see above comment)? That will help with debugging #36.

**Comment by andrey-norkin** [comment]
@EwoutH. BTW, I have added a flag that enables/disables Coveralls in #36 and switched them off for the time being. We should enable them based on some other variable than what compiler is used. Otherwise, the project may not build on systems that do not have Coveralls.

**Comment by kylophone** [comment]
> @kylophone @hassount Can Coveralls be enabled (see above comment)? That will help with debugging #36.

I will spend some time on this soon.

**Comment by EwoutH** [comment]
@kylophone It would be very nice if every commit to master would be ran against AWCY. Now I only see a single run on https://beta.arewecompressedyet.com/

**Comment by kylophone** [comment]
Test framework was merged. Let's enable tests in Travis.

**Comment by 1480c1** [comment]
I do not think that adding code coverage tests will be good for this project mainly because when running a coverage test, some of the instruction sets will not get used, meaning that most likely, the C_DEFAULT folder will stay around 10% and the rest of the folders at around ~50-~30%. <https://coveralls.io/github/1480c1/SVT-AV1?branch=coveralls>. 
Plus when using travis, the asm type is not always guaranteed (sometimes avx2[rare], most of the time ssse3, and others at random builds) and the percentage covered is not additive and so coverage will decrease and increase depending on the cpu used when provisioning.

**Comment by EwoutH** [comment]
@hassount @kylophone (and anyone else involved) Can we talk about CI today? I want to setup an extensive speed and coding performance framework, which should deliver a lot of useful metrics within a very short period (aiming for under 4 minutes). The basic idea is that you can comment on a PR with a certain string, a GitHub bot detects that, sends out encoding commands, collects and formats data and posts the data back to Git.

Main points of discussion are:
- Which input should be used (how many video's, which resolutions, how many frames, etc.)
- Which encoder settings should be tested (enc-modes, rate control, tiling, etc.)
- Which metrics should be returned (PSNR, SSIM, MS SSIM, VMAF, fps, cpu/memory usage)

Please ping me on IRC.

**Comment by 1480c1** [comment]
@EwoutH, could you possibly post information after it's sorted out somewhere accessable? I would also like to know about it, but am unable to really use irc on mobile

**Comment by EwoutH** [comment]
Will do.

**Comment by EwoutH** [comment]
@1480c1 What do you think of the new [GitHub Actions](https://github.com/features/actions)? Especially in comparison with Travis.

**Comment by 1480c1** [comment]
I have yet to test them since I only recently got access, but it does seem interesting since it's direct integration with GitHub plus I think it was 6 hours of build time allowed per build. I'm concerned about how to manage dependencies, but I will try it out soon

**Comment by EwoutH** [comment]
I just dived in a little deeper, build environments, dependencies and references are still in heavy development not documented that well. I hope this improves with the general release (13 november), for now Travis seems like the better option.

The tight integration with GitHub could be an advantage in the long term (and also a risk).

**Comment by EwoutH** [comment]
@hassount @tianjunwork Could one of you sign up for GitHub Actions Beta? Then we could slowly start with some testing of a GitHub Actions based CI. https://github.com/features/actions/signup/?account=OpenVisualCloud

**Comment by EwoutH** [comment]
@1480c1 We should add a 10-bit test case and a test case with resolution not dividable by 8 at some point.

**Comment by EwoutH** [comment]
@1480c1 You want to give it a go? https://twitter.com/travisci/status/1181257292018311176

> 📣You can now test your open source software on multiple CPU architectures✨ 
> 
> We’ve partnered with @Canonical @packethost and @Arm to make Arm-based builds available for free for your open source projects🎊

**Comment by 1480c1** [comment]
That's actually very interesting, however, SVT encoders only support x86_64 afaik

**Comment by 1480c1** [comment]
I might try it would with some other projects to see what's possible

**Comment by EwoutH** [comment]
@1480c1 If you disable the x86 specific assembly (AVX2 etc.) it should compile fine on Arm I think. Will take a look tomorrow.

**Comment by 1480c1** [comment]
I'll also see if that's possible, although I'm currently trying to write some cmakelists for vmaf as a side project

**Comment by 1480c1** [comment]
It may be possible to disable the simds using cmake on architectures other than x86

https://stackoverflow.com/questions/11944060/how-to-detect-target-architecture-using-cmake

**Comment by EwoutH** [comment]
@1480c1 Does the current build script ([Build/linux/build.sh](https://github.com/OpenVisualCloud/SVT-AV1/blob/master/Build/linux/build.sh)) allow for builds without assembly code? If so, which parameters do I have to pass?

**Comment by 1480c1** [comment]
No since that would require work on the cmakelists side, it's possible to make an option to exclude assembly code, but I also fear that would make a lot of undefined errors when trying to link

**Comment by EwoutH** [comment]
@1480c1 Currently a build on Arm looks like this: https://gist.github.com/EwoutH/e1e5df8e148f3d0a76d80fcb48bda61e

> it's possible to make an option to exclude assembly code, but I also fear that would make a lot of undefined errors when trying to link

Could you give that a try? I think it would increase general stability and compatibility greatly if SVT-AV1 also can be build and tested on plain C without assembly.

Ideally, at some point it would be possible to set different platforms (x86, ARMv8, POWER9) and then the CMake list determines which assembly code is build.

**Comment by 1480c1** [comment]
I could try after I finish my homework, it would be an interesting undertaking to say the least

**Comment by 1480c1** [comment]
@EwoutH `We’re excited to announce that GitHub Actions and GitHub Package Registry will be moving to general availability on November 13.` 

Maybe we can try the windows builds on github actions for multiple jobs instead of appveyor. My only problem with it is no between actions caching like ccache integrated and usable from github, it would require using a third-party storage. Supposedly might come mid-nov (https://github.community/t5/GitHub-Actions/Caching-files-between-GitHub-Action-executions/td-p/29445/page/2)

**Comment by EwoutH** [comment]
@1480c1 Preferably use both for some redundancy in the beginning. I'm going to wait a few weeks on the official release and for the codebase to stabilize a bit more before diving in.

BTW: If you want to experiment with compiling SVT-AV1 on Arm64 or other architectures, I have setup a branch with Travis CI customized for Arm64 here: https://github.com/EwoutH/SVT-AV1/tree/arm64-ci

**Comment by 1480c1** [comment]
> FYI: If you want to experiment with compiling SVT-AV1 on Arm64 or other architectures, I have setup a branch with Travis CI customized for Arm64 here: https://github.com/EwoutH/SVT-AV1/tree/arm64-ci

It seems that it might be better to wait until @spawlows finishes his set of [patches](https://github.com/OpenVisualCloud/SVT-AV1/pull/755) to see how SVT-AV1 will be moving forward for asm stuff, it may become easier to try to compile without x86 simds and use C only, or not

**Comment by 1480c1** [comment]
It seems github actions added caching https://github.com/actions/cache

**Comment by hassount** [comment]
@EwoutH do we still need this issue open ?

**Comment by EwoutH** [comment]
Nope
