### ISSUE TITLE
Code Cleanup

### ISSUE THREAD

**Issue by hassount** [OpenVisualCloud/SVT-AV1#668]
Now that the feature implementations are almost complete, Let's use this issue to set the items to be cleaned up. If you see something, please put it here:

**Phase 1:**
- [x] remove rate control mode 1
- [x] remove use_ssd as input to md_stage_0. 
- [x] remove decoupled_fast_loop_search_method and decouple_intra_inter_fast_loop
- [x] remove lcu from naming (e.g. mode_decision_configure_lcu to mode_decision_configure_sb)
- [x] port COST_CLEAN_UP from rtime-m0-test
- [x] remove fast_candidate_intra_count
- [x] LargestCodingUnit to SuperBlock
- [x] ConstrainedIntra @chkngit :)
- [x] CodingUnit to BlkStruct / cu_ptr to blk_ptr / cu_origin_x -y to blk_origin_x-y / 
- [x] reinforce snake_casing in code
- [x] change atb to tx_size _search
- [x] remove unused functions `void eb_av1_cdef_search()` and `void av1_cdef_search16bit()` in EbCdef.c
- [x] verify all of the commandline switches are documented and has valid checks for invalid input values #250 
- [x] remove in_loop_me_flag
- [x] remove useless MR_MODE checks (where M0 is already using the same setting)
- [x] remove check_skip_sub_blks()  and skip_sub_blks signal
- [x] rename copy_rbsp_bitstream_to_payload to copy_payload
- [x] remove ConstrainedIntra (@chkngit :) )
- [x] remove the following kernels (unused code)
- aom_lpf_vertical_4_dual_sse2
- aom_lpf_vertical_8_dual_c
- aom_lpf_vertical_14_dual_sse2/aom_lpf_vertical_14_dual_c
- aom_lpf_horizontal_4_dual_sse2
- aom_lpf_horizontal_14_dual_sse2
- aom_lpf_horizontal_8_dual_sse2/aom_lpf_horizontal_8_dual_c
- aom_highbd_lpf_vertical_14_dual_sse2/aom_highbd_lpf_vertical_14_dual_avx2
- aom_highbd_lpf_vertical_8_dual_avx2/aom_highbd_lpf_vertical_8_dual_sse2
- aom_highbd_lpf_vertical_4_dual_avx2/aom_highbd_lpf_vertical_4_dual_sse2
- aom_highbd_lpf_horizontal_14_dual_sse2/aom_highbd_lpf_horizontal_14_dual_avx2
- aom_highbd_lpf_horizontal_4_dual_sse2/aom_highbd_lpf_horizontal_4_dual_avx2
- aom_highbd_lpf_horizontal_8_dual_sse2/aom_highbd_lpf_horizontal_8_dual_avx2
- eb_av1_fwd_txfm2d_pf_32x32_c/eb_av1_fwd_txfm2d_pf_32x32_avx2
- smooth_v_predictor_c/eb_smooth_v_predictor_all_ssse3
- eb_smooth_h_predictor/eb_smooth_h_predictor_all_ssse3
- eb_aom_paeth_predictor_2x2
- eb_aom_highbd_dc_128_predictor_2x2
- eb_aom_highbd_dc_top_predictor_2x2_c
- eb_aom_highbd_h_predictor_2x2_c
- eb_aom_highbd_smooth_h_predictor_2x2
- eb_aom_highbd_smooth_v_predictor_2x2
- eb_aom_highbd_v_predictor_2x2
- highbd_variance64_c/highbd_variance64_avx2
- sum_residual_c/sum_residual8bit_avx2_intrin
- delete file EbMcp_Intrinsic_SSSE3.c
- compute8x8_satd_sse4
- delete file EbMcp_Intrinsic_SSE2.c
- intra_prediction_const_sse2
- residual_kernel_sub_sampled4x4_sse_intrin
- residual_kernel_sub_sampled8x8_sse2_intrin
- residual_kernel_sub_sampled16x16_sse2_intrin
- residual_kernel_sub_sampled32x32_sse2_intrin
- residual_kernel_sub_sampled64x64_sse2_intrin
- picture_addition_kernel16bit_sse2_intrin
- picture_addition_sse2
- picture_addition_kernel4x4_sse_intrin
- picture_addition_kernel8x8_sse2_intrin
- picture_addition_kernel16x16_sse2_intrin
- picture_addition_kernel32x32_sse2_intrin
- picture_addition_kernel64x64_sse2_intrin
- delete EbTransforms_Intrinsic_SSE2.c
- eb_aom_highbd_dc_predictor_32x16_sse2
- highbd_10_variance_sse2/highbd_12_variance_sse2
- delete transpose_sse2.c
- eb_aom_get_mb_ss_sse2
- variance_final_128_pel_sse2
- variance_final_256_pel_sse2
- variance_kernel_sse2
- variance4_sse2
- variance8_sse2
- aom_filter_block1d4_h4_avx2
- eb_copy_rect8_16bit_to_16bit_avx2
- all code under   PREDICT_NSQ_SHAPE including spatial_full_distortion_helper/spatial_full_distortion_avx2_helper
- [x] to rename the following functions according to coding style:
- Av1TransformTwoD_64x64_c
- Av1TransformTwoD_32x32_c
- Av1TransformTwoD_16x16_c
- Av1TransformTwoD_8x8_c
- Av1TransformTwoD_4x4_c
- HandleTransform16x64
- HandleTransform32x64
- HandleTransform64x16
- HandleTransform64x32
- HandleTransform64x64
- AvcStyleLumaIFCoeff8_SSSE3
- [x] blk_index instead of cuIndex @ mode_decision_sb().
- [x ] Global MV signal @ 2 diffrent process => to merge into 1.

**Comment by 1480c1** [comment]
Although this probably should belong in another issue, would it be possible to reduce the amount of public headers (`EbSvtAv1.h EbSvtAv1Dec.h EbSvtAv1Enc.h EbSvtAv1ErrorCodes.h EbSvtAv1ExtFrameBuf.h EbSvtAv1Formats.h`) by combining them or something similar before the next public release and before the api is stable?

**Comment by 1480c1** [comment]
Particularly across all of the SVT encoders

**Comment by hassount** [comment]
> Although this probably should belong in another issue, would it be possible to reduce the amount of public headers (`EbSvtAv1.h EbSvtAv1Dec.h EbSvtAv1Enc.h EbSvtAv1ErrorCodes.h EbSvtAv1ExtFrameBuf.h EbSvtAv1Formats.h`) by combining them or something similar before the next public release and before the api is stable?

@andrey-norkin any thoughts ?

**Comment by 1480c1** [comment]
Before 0.7.0, can https://github.com/OpenVisualCloud/SVT-AV1/issues/567 be addressed? Especially the conflicts with libaom since that's the most common lib people would probably link with ffmpeg

**Comment by JackZhouVCD** [comment]
not sure if this would fit in the list of items to add in the post so I'll write a comment instead, I found that the instructions to build the unit tests on windows are outdated:

https://github.com/OpenVisualCloud/SVT-AV1/blob/master/test/Readme.md

We no longer use `generate_vs17.bat` to build the solution.

**Comment by OmranAbdelkafi** [comment]
Working on the following item :

remove the following kernels (unused code)

aom_lpf_vertical_4_dual_sse2

aom_lpf_vertical_8_dual_c

aom_lpf_vertical_14_dual_sse2/aom_lpf_vertical_14_dual_c

aom_lpf_horizontal_4_dual_sse2

aom_lpf_horizontal_14_dual_sse2

aom_lpf_horizontal_8_dual_sse2/aom_lpf_horizontal_8_dual_c

aom_highbd_lpf_vertical_14_dual_sse2/aom_highbd_lpf_vertical_14_dual_avx2

aom_highbd_lpf_vertical_8_dual_avx2/aom_highbd_lpf_vertical_8_dual_sse2

aom_highbd_lpf_vertical_4_dual_avx2/aom_highbd_lpf_vertical_4_dual_sse2

aom_highbd_lpf_horizontal_14_dual_sse2/aom_highbd_lpf_horizontal_14_dual_avx2

aom_highbd_lpf_horizontal_4_dual_sse2/aom_highbd_lpf_horizontal_4_dual_avx2

aom_highbd_lpf_horizontal_8_dual_sse2/aom_highbd_lpf_horizontal_8_dual_avx2

eb_av1_fwd_txfm2d_pf_32x32_c/eb_av1_fwd_txfm2d_pf_32x32_avx2

smooth_v_predictor_c/eb_smooth_v_predictor_all_ssse3

eb_smooth_h_predictor/eb_smooth_h_predictor_all_ssse3

eb_aom_paeth_predictor_2x2

eb_aom_highbd_dc_128_predictor_2x2

eb_aom_highbd_dc_top_predictor_2x2_c

eb_aom_highbd_h_predictor_2x2_c

eb_aom_highbd_smooth_h_predictor_2x2

eb_aom_highbd_smooth_v_predictor_2x2

eb_aom_highbd_v_predictor_2x2

highbd_variance64_c/highbd_variance64_avx2

sum_residual_c/sum_residual8bit_avx2_intrin

delete file EbMcp_Intrinsic_SSSE3.c

compute8x8_satd_sse4

delete file EbMcp_Intrinsic_SSE2.c

intra_prediction_const_sse2

residual_kernel_sub_sampled4x4_sse_intrin

residual_kernel_sub_sampled8x8_sse2_intrin

residual_kernel_sub_sampled16x16_sse2_intrin

residual_kernel_sub_sampled32x32_sse2_intrin

residual_kernel_sub_sampled64x64_sse2_intrin

picture_addition_kernel16bit_sse2_intrin

picture_addition_sse2

picture_addition_kernel4x4_sse_intrin

picture_addition_kernel8x8_sse2_intrin

picture_addition_kernel16x16_sse2_intrin

picture_addition_kernel32x32_sse2_intrin

picture_addition_kernel64x64_sse2_intrin

delete EbTransforms_Intrinsic_SSE2.c

eb_aom_highbd_dc_predictor_32x16_sse2

highbd_10_variance_sse2/highbd_12_variance_sse2

delete transpose_sse2.c

eb_aom_get_mb_ss_sse2

variance_final_128_pel_sse2

variance_final_256_pel_sse2

variance_kernel_sse2

variance4_sse2

variance8_sse2

aom_filter_block1d4_h4_avx2

eb_copy_rect8_16bit_to_16bit_avx2

all code under PREDICT_NSQ_SHAPE including spatial_full_distortion_helper/spatial_full_distortion_avx2_helper

**Comment by hguermaz** [comment]
@OmranAbdelkafi  if not yet done then could you please keep ADD_SUPPORT_TO_SKIP_PART_N (present under PREDICT_NSQ_SHAPE ) or just assume ADD_SUPPORT_TO_SKIP_PART_N is always TRUE then remove the macro (should be lossless).
